// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jrvtftamtxtpqsjewcbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpydnRmdGFtdHh0cHFzamV3Y2J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3MzM3NjgsImV4cCI6MjA3NzMwOTc2OH0.uwL0enONbed25AZkhKx-pQ_7IfpBUcPx38dSxz3JAfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);